### ISSUE TITLE
error loading mods

### ISSUE THREAD

**Issue by fedekk2014** [JohnTheCoolingFan/PlutoniumEnergy#90] opened 2023-08-15 16:59 UTC
![factorio_xzq8kY7eav](https://github.com/JohnTheCoolingFan/PlutoniumEnergy/assets/65419172/8155160c-d217-4d6f-9e86-49764a32350d)

**Comment by JohnTheCoolingFan** [comment] 2023-08-15 17:06
The problem is caused by True Nukes.

**Comment by fedekk2014** [comment] 2023-08-15 17:10
so.. can you fix this?

**Comment by JohnTheCoolingFan** [comment] 2023-08-15 17:11
I have reported it to the True Nukes mod author. I can take a look at it and see what got broken and try to fix, but I won't promise.

**Comment by More-Wrong** [comment] 2023-08-15 22:53
Should be fixed in T-N now. Thanks for the fix!

**Closed** 2023-08-16 00:11 UTC
